### mini-Makefile for minisat subdirectories --- 

## Author: antonb
## Keywords: 
## X-URL: 

#-------------------------------------------------------------------------------
# Define source root, the target name and include standard defs
#-------------------------------------------------------------------------------

ROOT = ../../../..

-include $(ROOT)/makefile-includes    # Configuration of BOLT

INCS += includes idman
EXTINCS += minisat-hmuc

-include $(MKDIR)/makefile-common-defs

CXXFLAGS := $(CFLAGS)

#-------------------------------------------------------------------------------

### Makefile ends here
