### Makefile --- 

#-------------------------------------------------------------------------------
# Define source root, the target name and include standard defs
#-------------------------------------------------------------------------------

ROOT = ../../..

TRGT = ubcsat12

-include $(ROOT)/makefile-includes    # Configuration of BOLT

LNKFLAGS += -lm
CPPFLAGS += -x c++

-include $(MKDIR)/makefile-common-defs

#-------------------------------------------------------------------------------

### Makefile ends here
