### Makefile --- 

## Author: jpms
## Version: $Id: Makefile 73 2007-07-26 15:16:48Z jpms $
## Keywords: 
## X-URL: 

#-------------------------------------------------------------------------------
# Define source root, the target name and include standard defs
#-------------------------------------------------------------------------------

ROOT = ../..

-include $(ROOT)/makefile-includes    # Configuration of BOLT

TRGT = clset

INCS += include idman

-include $(MKDIR)/makefile-common-defs

#-------------------------------------------------------------------------------

### Makefile ends here
