### mini-Makefile for minisat subdirectories --- 

## Author: antonb
## Keywords: 
## X-URL: 

#-------------------------------------------------------------------------------
# Define source root, the target name and include standard defs
#-------------------------------------------------------------------------------

ROOT = ../../../..

-include $(ROOT)/makefile-includes    # Configuration of BOLT

CPPFLAGS += 

INCS += includes idman
EXTINCS += glucose30

-include $(MKDIR)/makefile-common-defs

#-------------------------------------------------------------------------------

### Makefile ends here
