### Makefile --- 
##
## Author:   antonb
##

#-------------------------------------------------------------------------------
# Define source root, the target name and include standard defs
#-------------------------------------------------------------------------------

ROOT = ../../..

TRGT = minisat22-2

-include $(ROOT)/makefile-includes    # Configuration of BOLT

INCS += include tlog idman clset wraps-2 mus-2 # mus-2 only for basic_group_set.hh

-include $(MKDIR)/makefile-common-defs

# Extra flags for minisat (moved them into mtl/IntTypes.h)
#CPPFLAGS += -D __STDC_LIMIT_MACROS -D __STDC_FORMAT_MACROS

### Makefile ends here
