### Makefile for picosat-954 --- 

## Author: antonb
## Keywords: 
## X-URL: 

#-------------------------------------------------------------------------------
# Define source root, the target name and include standard defs
#-------------------------------------------------------------------------------

ROOT = ../../..

TRGT = lingeling-ala

-include $(ROOT)/makefile-includes    # Configuration of BOLT

INCS += 
EXTINCS += lingeling-ala

-include $(MKDIR)/makefile-common-defs

CXXFLAGS += -w -fpermissive -DNLGLOG -DNDEBUG -DNCHKSOL -DNLGLPICOSAT

#-------------------------------------------------------------------------------

### Makefile ends here
