### Makefile for picosat-954 --- 

## Author: antonb
## Keywords: 
## X-URL: 

#-------------------------------------------------------------------------------
# Define source root, the target name and include standard defs
#-------------------------------------------------------------------------------

ROOT = ../../..

TRGT = picosat954

-include $(ROOT)/makefile-includes    # Configuration of BOLT

INCS += 
EXTINCS += picosat954

-include $(MKDIR)/makefile-common-defs

CXXFLAGS += -w -fpermissive

#-------------------------------------------------------------------------------

### Makefile ends here
