### Makefile --- 
##
## Author:   jpms, antonb
##
##

#-------------------------------------------------------------------------------
# Define source root, the target name and include standard defs
#-------------------------------------------------------------------------------

ROOT = ../..

-include $(ROOT)/makefile-includes    # Configuration of BOLT

TRGT = wraps-2

CPPFLAGS += 

INCS += includes idman clset wraps mus-2 # mus-2 only for basic_group_set.hh

EXTRALIBS = 

-include $(MKDIR)/makefile-common-defs

#-------------------------------------------------------------------------------

### Makefile ends here
