### Makefile --- 
##
## Author:   jpms, antonb
##

#-------------------------------------------------------------------------------
# Define source root, the target name and include standard defs
#-------------------------------------------------------------------------------

ROOT = ../..

-include $(ROOT)/makefile-includes    # Configuration of BOLT

TRGT = wraps-2

INCS += include idman clset mus-2 # mus-2 only for basic_group_set.hh
EXTINCS += minisat22-2

EXTRALIBS += 

-include $(MKDIR)/makefile-common-defs

#-------------------------------------------------------------------------------

### Makefile ends here
